### ISSUE TITLE
The code runs normally, but there is no output

### ISSUE THREAD

**Issue by Qvital** [jake3991/sonar-SLAM#4]
I am trying to run this demo. Although I checked the Python dependency and changed the interpreter to python3, my program does not output an image, "No Image". And there is nothing below rviz.
![Kazam_screenshot_00035](https://user-images.githubusercontent.com/39051305/201038535-069fe697-b3fd-4d9f-917c-6d7af8757de8.png)
![Kazam_screenshot_00037](https://user-images.githubusercontent.com/39051305/201038733-f1acccab-6625-471d-b2d7-c374e329451c.png)
I hope I can get your help.

**Comment by jake3991** [comment]
Thanks for your interest in sonar-SLAM! 

Once you call the launch file and everything starts (as you have done), you will need to playback some data. We have an opensource dataset link here from the readme (https://drive.google.com/file/d/1nmiFfyk8mVssLqgac7BOe4_RPBP6Wnc9/view?usp=sharing). You can just download, open a new terminal, and run the following.

```
rosbag play sample_data.bag
```

Let me know if you have any further issues!

**Comment by jake3991** [comment]
@Qvital checking in here. Did that help?

**Comment by Qvital** [comment]
I solved the problem successfully. Thank you very much.

**Comment by jake3991** [comment]
Great!
