### ISSUE TITLE
ModuleNotFoundError: No module named 'bruce_slam'

### ISSUE THREAD

**Issue by Nicococozz** [jake3991/sonar-SLAM#6]
Hello there,
When I tried to excute _roslaunch bruce_slam slam.launch file:=path_to_data/your_data.bag_, an error message poped up, please see the followed image for the detail. 
![8ecdf36a7875ea26a3f02201e8dfb42](https://user-images.githubusercontent.com/91198806/234177543-d2acda89-6f24-4487-8852-33d34ea96519.png)
Do you know what caused this error? and how to fixed this？

Thank you for the help.

**Comment by jake3991** [comment]
Hello @Nicococozz, and thanks for your interest in sonar-SLAM! 

I'm having trouble replicating the issue on my side. I have a few questions. 

- What version of Ubuntu are you using? 
- What version of ROS?
- Did the code compile correctly?
- Did you call source/catkin_ws/devel/setup.bash?
- Did you try running the system using the "online" method? Trying that would give me a better idea of what is going on.

Online mode

```
source catkin_ws/devel/setup.bash

roslaunch bruce_slam slam.launch
```

Open a second terminal window. 
``rosbag play your_data.bag
``

Please make sure you pull the most recent code before running these tests!

**Comment by Nicococozz** [comment]
Thank you so much for your quick reply. My Ubuntu is 20.04 and ROS is noetic. I used catkin build not catkin_make and I did source ~/catkin_ws/devel/setup.bash. I also tried to run roslaunch bruce_slam slam.launch, and I still got the same error message. 
![image](https://user-images.githubusercontent.com/91198806/234313094-7976afcb-90c0-4d52-a90f-b16b2fe34a9c.png)

![image](https://user-images.githubusercontent.com/91198806/234313143-77052f33-48e0-4169-82e9-b2c7919e6e38.png)

**Comment by jake3991** [comment]
No problem! 

I see you are sourcing .bashrc, but not exactly as written below. 
```
source devel/setup.bash
```
Can you try running the above command and then the roslaunch?

**Comment by Nicococozz** [comment]
I run the exactly same code I got the following error message
![image](https://user-images.githubusercontent.com/91198806/234323885-7c76227e-e35e-4aea-9d0b-1e9c7a6ed145.png)
It seems like I did not sourced successfully.

Did I compiled the file in a wrong way? or Did I miss any package?

**Comment by jake3991** [comment]
It looks like nothing is getting built at all. See the line that says the following:
```
All 0 packages succeeded!
```
Is the code in catkin_ws/src?
What do you get from the following command in your catkin_ws?
```
ls
```

**Comment by Lowkeydriver** [comment]
Hi Jake. Soz but i had same issues here as well
![image](https://github.com/jake3991/sonar-SLAM/assets/128971492/99d6f175-46b6-421a-8a53-1706fbe3e6ae)

![image](https://github.com/jake3991/sonar-SLAM/assets/128971492/6ac19933-e173-43df-a8d3-d1da2e58cdbb)
and when i use catkin build. only 11 of 15 packages succeeded
![image](https://github.com/jake3991/sonar-SLAM/assets/128971492/f1e8d721-afd1-427d-b62f-c936ebe44770)
