### ISSUE TITLE
Almost Completed Compile

### ISSUE THREAD

**Issue by zhughesjd** [jake3991/sonar-SLAM#7]
Greetings @jake3991 
First off, nice job here
Very impressed with your work

--------

Was able to compile 14 out of 15 packages

![image](https://github.com/jake3991/sonar-SLAM/assets/4139088/686ce73d-6bcc-47a1-b63a-f059f291b903)

It looks like the point cloud library (pcl) is giving me fits for **catkin build**
Running ros noetic / ubuntu 20.04
Followed the install of all your python3 and ROS dependencies using either apt-get or pip

Have you seen this before?
Could I have installed a dependency incorrectly?

here are a couple more pcl errors:

![image](https://github.com/jake3991/sonar-SLAM/assets/4139088/09289cbc-6b07-490b-9c3b-11c7f96941f5)

![image](https://github.com/jake3991/sonar-SLAM/assets/4139088/06d69860-8888-4bfb-a288-03a9dcfe0e09)

**Comment by jake3991** [comment]
Thanks! 

I have a few questions.
1. Can you post the error message at the top? The first one that occurs? 
2. Did you clone these repos into the src folder?
clone https://github.com/ethz-asl/libnabo.git into your catkin workspace
clone https://github.com/ethz-asl/libpointmatcher.git into your catkin workspace
clone https://github.com/jake3991/Argonaut.git into your catkin workspace

**Comment by zhughesjd** [comment]
Thanks for the quick response
So I did  clone all 4 github repos into the src folder
The error in the picture above is caused by missing logs of a missing logs directory
Was able to fix this in a cleaned catkin_ws by creating a directory called logs
"mkdir logs"

Still having a problem though
extended my terminal buffer alot to see the original error
Looks like the pcl library requires C++14
(See  screenshot below)

Any idea on how to fix this?

![image](https://github.com/jake3991/sonar-SLAM/assets/4139088/0e3bdf29-6311-41e1-96be-ed4aab829e39)

**Comment by jake3991** [comment]
Oh interesting, maybe we can tweak the build a bit. Could you try these steps?
1. catkin clean 
2. Change line 4 in this file to be as below https://github.com/jake3991/sonar-SLAM/blob/main/bruce_slam/CMakeLists.txt:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -O3")
```
3. Recompile

**Comment by zhughesjd** [comment]
Changed the line 4 to reflect your suggestion above
No luck
Same error
:(

**Comment by jake3991** [comment]
I can't replicate the bug on my side but I did find a thread when searching for your error. 

https://github.com/PointCloudLibrary/pcl/issues/2968

Let me know f you are able to fix it!

**Comment by zhughesjd** [comment]
Thanks for the link and help above

will let you know what i find

**Comment by jake3991** [comment]
In case it ends up being relevant, I'm using PCL version 1.10

**Comment by zhughesjd** [comment]
Thanks for the info, might be useful
Didn't have any luck yesterday

Below is a little gem for you
It is my shell commands installing (almost) all the dependencies this repo requires
Let me know if I am installing any dependencies incorrectly
Feel free to put this in an appropriate place in this repo:

------------------------------------------------------

sudo apt -y update
sudo apt -y upgrade

sudo apt install -y python3-cv-bridge
sudo pip install -y gtsam
sudo pip install matplotlib
sudo apt install -y python3-message-filters
sudo apt install -y python3-numpy
sudo pip install opencv_python
sudo apt install -y ros-noetic-rosbag
sudo apt install -y ros-noetic-rospy
sudo pip install scikit_learn
sudo pip install scipy
sudo apt install -y ros-noetic-sensor-msgs
sudo pip install Shapely
sudo apt install -y ros-noetic-tf
sudo pip install tqdm
sudo pip install pyyaml

sudo apt install -y ros-noetic-pybind11-catkin
sudo pip install catkin-tools

**Comment by zhughesjd** [comment]
Might be a hardware issue for me
Using a laptop with no nvidia card ubuntu 20.04

What hardware system are you using?

**Comment by jake3991** [comment]
I'm indeed using an NVIDIA graphics card. I also have an Intel processor. @pszenher have you seen this bug before?

**Comment by mokby** [comment]
I have the same issue and I solved this ,open CmakeLists.txt under bruce_slam,and add this
`add_compile_options(-std=c++11 )
add_compile_options(-std=c++14 )
set(CMAKE_CXX_STANDARD 14)`

**Comment by mokby** [comment]
Recommend to clean the build and devel folder first and then run catkin build

**Comment by jake3991** [comment]
Marking as resolved.
