### ISSUE TITLE
libpointmatcher build fails

### ISSUE THREAD

**Issue by Tunjii10** [jake3991/sonar-SLAM#8]
Hello, thanks for your awesome work.
I am having some setup issues with the project. I have been able to clone the repositories and install the necessary libraries but on running `catkin build ` i get this error

`-----------------------------------------------------------
Profile:                     default
Extending:        [explicit] /opt/ros/noetic
Workspace:                   /home/favour/catkin_ws
-----------------------------------------------------------
Build Space:        [exists] /home/favour/catkin_ws/build
Devel Space:        [exists] /home/favour/catkin_ws/devel
Install Space:      [unused] /home/favour/catkin_ws/install
Log Space:          [exists] /home/favour/catkin_ws/logs
Source Space:       [exists] /home/favour/catkin_ws/src
DESTDIR:            [unused] None
-----------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-----------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-----------------------------------------------------------
Buildlisted Packages:        None
Skiplisted Packages:         None
-----------------------------------------------------------
Workspace configuration appears valid.
-----------------------------------------------------------
[build] Found 16 packages in 0.0 seconds.
[build] Updating package table.
Starting  >>> bluerov_bridge
Starting  >>> bruce
Starting  >>> bruce_msgs
Starting  >>> kvh_gyro
Starting  >>> libnabo
Starting  >>> rti_dvl
Starting  >>> sonar_oculus
Starting  >>> uuv_sensor_msgs
Starting  >>> vectornav
Starting  >>> waterlinked_gps
Finished  <<< rti_dvl                         [ 0.4 seconds ]
Finished  <<< kvh_gyro                        [ 0.3 seconds ]
Finished  <<< sonar_oculus                    [ 0.4 seconds ]
Finished  <<< bluerov_bridge                  [ 0.2 seconds ]
Starting  >>> bar30_depth
Starting  >>> bluerov_control
Finished  <<< vectornav                       [ 0.4 seconds ]
Finished  <<< waterlinked_gps                 [ 0.2 seconds ]
Finished  <<< uuv_sensor_msgs                 [ 0.4 seconds ]
Starting  >>> grpc_ros_adapter
Finished  <<< bluerov_control                 [ 0.2 seconds ]
Finished  <<< bar30_depth                     [ 0.3 seconds ]
Starting  >>> bluerov_launch
Finished  <<< libnabo                         [ 0.6 seconds ]
Starting  >>> libpointmatcher
Finished  <<< grpc_ros_adapter                [ 0.3 seconds ]
Finished  <<< bluerov_launch                  [ 0.2 seconds ]
_____________________________________________________________________
Warnings   << bruce:check /home/favour/catkin_ws/logs/bruce/build.check.010.log
CMake Warning (dev) at CMakeLists.txt:2 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

cd /home/favour/catkin_ws/build/bruce; catkin build --get-env bruce | catkin env -si  /usr/bin/make cmake_check_build_system; cd -

.....................................................................
Finished  <<< bruce                           [ 7.5 seconds ]
_____________________________________________________________________
Warnings   << bruce_msgs:check /home/favour/catkin_ws/logs/bruce_msgs/build.check.010.log
CMake Warning (dev) at CMakeLists.txt:2 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

cd /home/favour/catkin_ws/build/bruce_msgs; catkin build --get-env bruce_msgs | catkin env -si  /usr/bin/make cmake_check_build_system; cd -

.....................................................................
Finished  <<< bruce_msgs                      [ 9.1 seconds ]
_____________________________________________________________________
Errors     << libpointmatcher:make /home/favour/catkin_ws/logs/libpointmatcher/build.make.010.log
In file included from /home/favour/catkin_ws/src/libpointmatcher/pointmatcher/DataPointsFilters/SurfaceNormal.cpp:43:
/home/favour/catkin_ws/src/libpointmatcher/pointmatcher/MatchersImpl.h:41:10: fatal error: nabo/nabo.h: No such file or directory
   41 | #include "nabo/nabo.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pointmatcher.dir/build.make:570: CMakeFiles/pointmatcher.dir/pointmatcher/DataPointsFilters/SurfaceNormal.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/favour/catkin_ws/src/libpointmatcher/pointmatcher/MatchersImpl.cpp:36:
/home/favour/catkin_ws/src/libpointmatcher/pointmatcher/MatchersImpl.h:41:10: fatal error: nabo/nabo.h: No such file or directory
   41 | #include "nabo/nabo.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
In file included from /home/favour/catkin_ws/src/libpointmatcher/pointmatcher/OutlierFiltersImpl.cpp:39:
/home/favour/catkin_ws/src/libpointmatcher/pointmatcher/MatchersImpl.h:41:10: fatal error: nabo/nabo.h: No such file or directory
   41 | #include "nabo/nabo.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pointmatcher.dir/build.make:336: CMakeFiles/pointmatcher.dir/pointmatcher/MatchersImpl.cpp.o] Error 1
make[2]: *** [CMakeFiles/pointmatcher.dir/build.make:349: CMakeFiles/pointmatcher.dir/pointmatcher/OutlierFiltersImpl.cpp.o] Error 1
In file included from /home/favour/catkin_ws/src/libpointmatcher/pointmatcher/DataPointsFilters/SpectralDecomposition.h:38,
                 from /home/favour/catkin_ws/src/libpointmatcher/pointmatcher/DataPointsFiltersImpl.h:67,
                 from /home/favour/catkin_ws/src/libpointmatcher/pointmatcher/ICP.cpp:42:
/home/favour/catkin_ws/src/libpointmatcher/pointmatcher/DataPointsFilters/utils/sparsetv.h:39:10: fatal error: nabo/nabo.h: No such file or directory
   39 | #include <nabo/nabo.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pointmatcher.dir/build.make:115: CMakeFiles/pointmatcher.dir/pointmatcher/ICP.cpp.o] Error 1
In file included from /home/favour/catkin_ws/src/libpointmatcher/pointmatcher/DataPointsFilters/SpectralDecomposition.h:38,
                 from /home/favour/catkin_ws/src/libpointmatcher/pointmatcher/DataPointsFiltersImpl.h:67,
                 from /home/favour/catkin_ws/src/libpointmatcher/pointmatcher/Registry.cpp:40:
/home/favour/catkin_ws/src/libpointmatcher/pointmatcher/DataPointsFilters/utils/sparsetv.h:39:10: fatal error: nabo/nabo.h: No such file or directory
   39 | #include <nabo/nabo.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/pointmatcher.dir/build.make:128: CMakeFiles/pointmatcher.dir/pointmatcher/Registry.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:202: CMakeFiles/pointmatcher.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
cd /home/favour/catkin_ws/build/libpointmatcher; catkin build --get-env libpointmatcher | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

.....................................................................
Failed     << libpointmatcher:make            [ Exited with code 2 ]
Failed    <<< libpointmatcher                 [ 30.1 seconds ]
Abandoned <<< bruce_slam                      [ Unrelated job failed ]
[build] Summary: 14 of 16 packages succeeded.
[build]   Ignored:   None.
[build]   Warnings:  2 packages succeeded with warnings.
[build]   Abandoned: 1 packages were abandoned.
[build]   Failed:    1 packages failed.
[build] Runtime: 32.4 seconds total.` 

I am a bit confused, are there any step to take to compiling the other external libraries and would you mind listing the version of libnabo and libpointmatcher you use for running your code.

**Comment by jake3991** [comment]
Thanks for raising this issue! It's been a long time since I have cloned direct from the libpoint matcher repo and some major changes have been made. I was able to find the version of it we are working with at present. Please let me know if the instructions below resolve your issue!

```
catkin clean
```
delete the libpointmatcher folder
```
git clone https://github.com/ethz-asl/libpointmatcher.git
cd libpointmatcher
git checkout d478ef2eb33894d5f1fe84d8c62cec2fc6da818f
cd ..
catkin build
```

**Comment by jake3991** [comment]
@ivanacollg, tagging you to make you aware of this

**Comment by Tunjii10** [comment]
@jake3991 yes it did. Thanks alot.

**Comment by jake3991** [comment]
@Tunjii10 great thanks for verifying! I have updated the readme to reflect this thread. Thanks for raising and helping correct this issue. 

https://github.com/jake3991/sonar-SLAM/commit/2143ae0675a74f4a279aea42af44d886c8e4e000
