### ISSUE TITLE
pcl import error

### ISSUE THREAD

**Issue by GHz12138** [jake3991/sonar-SLAM#9]
I have compiled it successfully
![2023-08-16 20-48-04 的屏幕截图](https://github.com/jake3991/sonar-SLAM/assets/103635643/8f64b1fc-7eda-4cda-862e-baf354b1557a)

In the roslaunch slam.launch file, this error occurred
![2023-08-16 20-45-02 的屏幕截图](https://github.com/jake3991/sonar-SLAM/assets/103635643/b85bdabc-8854-48af-a899-e2982c913434)

**Comment by tantingfeng** [comment]
I'm having the same problem and don't know how to fix it

**Comment by GHz12138** [comment]
I deleted the sona-SLAM project file from src, then downloaded and compiled it again to run, if this does not work, you can check that the dependencies are installed correctly

**Comment by GHz12138** [comment]
I have run the data sample of sample.bag given by the project. May I ask what is the cause of Constraints and Marker status warning at the bottom right of the picture
![2023-08-21 11-55-53 的屏幕截图](https://github.com/jake3991/sonar-SLAM/assets/103635643/a9b8b01c-7a02-45c3-8f56-56a87651865c)

**Comment by jake3991** [comment]
Thanks for your interest in the repo!

Glad you got things running. I can't quite tell from that screenshot, but can you let the bag play a little longer and verify you can see the following items? If the warning is present and the vis works it's not an issue. 
- Multi-colored boxes showing each robot pose
- Green lines connecting poses

**Comment by GHz12138** [comment]
Thanks for your timely reply. I can run the sample.bag data set without error, but the status of Marker and Constaints are always abnormal during the process, is there any problem?
![2023-08-21 22-33-02 的屏幕截图](https://github.com/jake3991/sonar-SLAM/assets/103635643/6fe644e3-c560-40a7-86ed-c3a9142e7948)
![2023-08-21 22-33-28 的屏幕截图](https://github.com/jake3991/sonar-SLAM/assets/103635643/a22e478c-b07c-4ff2-a533-287238a3cb0e)

**Comment by jake3991** [comment]
That is normal. Those marker warnings are typically there, we have to do some fancy tricks with the markers to make those nice lines show up and RVIZ displays a warning. 

Looks like things are working well.
